language: generic
sudo: false

env:
    global:
    - BYOND_MAJOR="510"
    - BYOND_MINOR="1332"
    - NODE_VERSION="4"
    - BUILD_TOOLS=false
    - DM_MAPFILE=""
    matrix:
    - DM_MAPFILE="lolnone"


cache:
  directories:
    - $HOME/BYOND-${BYOND_MAJOR}.${BYOND_MINOR}


addons:
  apt:
    packages:
      - libc6-i386
      - libgcc1:i386
      - libstdc++6:i386

install:
  - tools/travis/install_build_tools.sh

before_script:
  - tools/travis/before_build_tools.sh
  - tools/travis/before_build_byond.sh

script:
  - tools/travis/check_filedirs.sh tgstation.dme
  - tools/travis/build_tools.sh
  - tools/travis/build_byond.sh
